// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.fundatiacomunitarabucuresti.volunteer.domain.Authority;
import ro.fundatiacomunitarabucuresti.volunteer.domain.AuthorityDataOnDemand;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccount;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccountDataOnDemand;

privileged aspect AuthorityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AuthorityDataOnDemand: @Component;
    
    private Random AuthorityDataOnDemand.rnd = new SecureRandom();
    
    private List<Authority> AuthorityDataOnDemand.data;
    
    @Autowired
    UserAccountDataOnDemand AuthorityDataOnDemand.userAccountDataOnDemand;
    
    public Authority AuthorityDataOnDemand.getNewTransientAuthority(int index) {
        Authority obj = new Authority();
        setAuthority(obj, index);
        setUserAccount(obj, index);
        return obj;
    }
    
    public void AuthorityDataOnDemand.setAuthority(Authority obj, int index) {
        String authority = "authority_" + index;
        obj.setAuthority(authority);
    }
    
    public void AuthorityDataOnDemand.setUserAccount(Authority obj, int index) {
        UserAccount userAccount = userAccountDataOnDemand.getRandomUserAccount();
        obj.setUserAccount(userAccount);
    }
    
    public Authority AuthorityDataOnDemand.getSpecificAuthority(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Authority obj = data.get(index);
        Long id = obj.getId();
        return Authority.findAuthority(id);
    }
    
    public Authority AuthorityDataOnDemand.getRandomAuthority() {
        init();
        Authority obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Authority.findAuthority(id);
    }
    
    public boolean AuthorityDataOnDemand.modifyAuthority(Authority obj) {
        return false;
    }
    
    public void AuthorityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Authority.findAuthorityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Authority' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Authority>();
        for (int i = 0; i < 10; i++) {
            Authority obj = getNewTransientAuthority(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
