// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.fundatiacomunitarabucuresti.volunteer.domain.Organization;
import ro.fundatiacomunitarabucuresti.volunteer.domain.OrganizationDataOnDemand;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccountDataOnDemand;

privileged aspect OrganizationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrganizationDataOnDemand: @Component;
    
    private Random OrganizationDataOnDemand.rnd = new SecureRandom();
    
    private List<Organization> OrganizationDataOnDemand.data;
    
    @Autowired
    UserAccountDataOnDemand OrganizationDataOnDemand.userAccountDataOnDemand;
    
    public Organization OrganizationDataOnDemand.getNewTransientOrganization(int index) {
        Organization obj = new Organization();
        setName(obj, index);
        setWebsite(obj, index);
        return obj;
    }
    
    public void OrganizationDataOnDemand.setName(Organization obj, int index) {
        String name = "name_" + index;
        if (name.length() > 250) {
            name = new Random().nextInt(10) + name.substring(1, 250);
        }
        obj.setName(name);
    }
    
    public void OrganizationDataOnDemand.setWebsite(Organization obj, int index) {
        String website = "website_" + index;
        obj.setWebsite(website);
    }
    
    public Organization OrganizationDataOnDemand.getSpecificOrganization(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Organization obj = data.get(index);
        Long id = obj.getId();
        return Organization.findOrganization(id);
    }
    
    public Organization OrganizationDataOnDemand.getRandomOrganization() {
        init();
        Organization obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Organization.findOrganization(id);
    }
    
    public boolean OrganizationDataOnDemand.modifyOrganization(Organization obj) {
        return false;
    }
    
    public void OrganizationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Organization.findOrganizationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Organization' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Organization>();
        for (int i = 0; i < 10; i++) {
            Organization obj = getNewTransientOrganization(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
