// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccount;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccountDataOnDemand;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccountIntegrationTest;

privileged aspect UserAccountIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAccountIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAccountIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAccountIntegrationTest: @Transactional;
    
    @Autowired
    UserAccountDataOnDemand UserAccountIntegrationTest.dod;
    
    @Test
    public void UserAccountIntegrationTest.testCountUserAccounts() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        long count = UserAccount.countUserAccounts();
        Assert.assertTrue("Counter for 'UserAccount' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAccountIntegrationTest.testFindUserAccount() {
        UserAccount obj = dod.getRandomUserAccount();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide an identifier", id);
        obj = UserAccount.findUserAccount(id);
        Assert.assertNotNull("Find method for 'UserAccount' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAccount' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAccountIntegrationTest.testFindAllUserAccounts() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        long count = UserAccount.countUserAccounts();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAccount', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAccount> result = UserAccount.findAllUserAccounts();
        Assert.assertNotNull("Find all method for 'UserAccount' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAccount' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAccountIntegrationTest.testFindUserAccountEntries() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        long count = UserAccount.countUserAccounts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAccount> result = UserAccount.findUserAccountEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAccount' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAccount' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAccountIntegrationTest.testFlush() {
        UserAccount obj = dod.getRandomUserAccount();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide an identifier", id);
        obj = UserAccount.findUserAccount(id);
        Assert.assertNotNull("Find method for 'UserAccount' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserAccount(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserAccount' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAccountIntegrationTest.testMergeUpdate() {
        UserAccount obj = dod.getRandomUserAccount();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide an identifier", id);
        obj = UserAccount.findUserAccount(id);
        boolean modified =  dod.modifyUserAccount(obj);
        Integer currentVersion = obj.getVersion();
        UserAccount merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserAccount' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAccountIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", dod.getRandomUserAccount());
        UserAccount obj = dod.getNewTransientUserAccount(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserAccount' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserAccount' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAccountIntegrationTest.testRemove() {
        UserAccount obj = dod.getRandomUserAccount();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccount' failed to provide an identifier", id);
        obj = UserAccount.findUserAccount(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAccount' with identifier '" + id + "'", UserAccount.findUserAccount(id));
    }
    
}
