// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccount;
import ro.fundatiacomunitarabucuresti.volunteer.domain.UserAccountDataOnDemand;
import ro.fundatiacomunitarabucuresti.volunteer.domain.Volunteer;
import ro.fundatiacomunitarabucuresti.volunteer.domain.VolunteerDataOnDemand;

privileged aspect VolunteerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VolunteerDataOnDemand: @Component;
    
    private Random VolunteerDataOnDemand.rnd = new SecureRandom();
    
    private List<Volunteer> VolunteerDataOnDemand.data;
    
    @Autowired
    UserAccountDataOnDemand VolunteerDataOnDemand.userAccountDataOnDemand;
    
    public Volunteer VolunteerDataOnDemand.getNewTransientVolunteer(int index) {
        Volunteer obj = new Volunteer();
        setUserAccount(obj, index);
        return obj;
    }
    
    public void VolunteerDataOnDemand.setUserAccount(Volunteer obj, int index) {
        UserAccount userAccount = userAccountDataOnDemand.getRandomUserAccount();
        obj.setUserAccount(userAccount);
    }
    
    public Volunteer VolunteerDataOnDemand.getSpecificVolunteer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Volunteer obj = data.get(index);
        Long id = obj.getId();
        return Volunteer.findVolunteer(id);
    }
    
    public Volunteer VolunteerDataOnDemand.getRandomVolunteer() {
        init();
        Volunteer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Volunteer.findVolunteer(id);
    }
    
    public boolean VolunteerDataOnDemand.modifyVolunteer(Volunteer obj) {
        return false;
    }
    
    public void VolunteerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Volunteer.findVolunteerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Volunteer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Volunteer>();
        for (int i = 0; i < 10; i++) {
            Volunteer obj = getNewTransientVolunteer(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
