// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import ro.fundatiacomunitarabucuresti.volunteer.domain.City;

privileged aspect City_Roo_JavaBean {
    
    public String City.getCity() {
        return this.city;
    }
    
    public void City.setCity(String city) {
        this.city = city;
    }
    
}
